sudo: false

language: node_js
node_js:
  - 4
  - 6

cache:
  yarn: true

before_install:
  - yarn global add coveralls
  - git config --global user.email "jonathan.buchanan@gmail.com"
  - git config --global user.name "Jonny Buchanan"

script: "yarn coverage"

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
    - next
