branches:
  only:
  - master
  - next

environment:
  matrix:
  - nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - yarn --version
  - yarn coverage

build: off

cache:
 - "%LOCALAPPDATA%\\Yarn"
